# .___  ___.      ___   .___________.___________. __    __   __   _______  __    __  
# |   \/   |     /   \  |           |           ||  |  |  | |  | |   ____||  |  |  | 
# |  \  /  |    /  ^  \ `---|  |----`---|  |----`|  |__|  | |  | |  |__   |  |  |  | 
# |  |\/|  |   /  /_\  \    |  |        |  |     |   __   | |  | |   __|  |  |  |  | 
# |  |  |  |  /  _____  \   |  |        |  |     |  |  |  | |  | |  |____ |  `--'  | 
# |__|  |__| /__/     \__\  |__|        |__|     |__|  |__| |__| |_______| \______/  

# 888     888 8888888b.        d8888  .d8888b.  8888888b.         d8888 888b     d888 
# 888     888 888  "Y88b      d88888 d88P  Y88b 888   Y88b       d88888 8888b   d8888 
# 888     888 888    888     d88P888 888    888 888    888      d88P888 88888b.d88888 
# 888     888 888    888    d88P 888 888        888   d88P     d88P 888 888Y88888P888 
# 888     888 888    888   d88P  888 888  88888 8888888P"     d88P  888 888 Y888P 888 
# 888     888 888    888  d88P   888 888    888 888 T88b     d88P   888 888  Y8P  888 
# Y88b. .d88P 888  .d88P d8888888888 Y88b  d88P 888  T88b   d8888888888 888   "   888 
#  "Y88888P"  8888888P" d88P     888  "Y8888P88 888   T88b d88P     888 888       888
                                                                     
#      _________    _  _   ___ ____    _____ ___     ___  _    ___  _ 
#   _ |___ |___ \  | || | / _ |___ \  |___  ( _ )   / _ \/ |  / _ \/ |
# _| |_ |_ \ __) | | || || (_) |__) |    / // _ \  | (_) | | | | | | |
#|_   ____) / __/  |__   _\__, / __/    / /| (_) |  \__, | | | |_| | |
#  |_||____|_____|    |_|   /_|_____|  /_/  \___/     /_/|_|  \___/|_|

Description: 'CloudFormation network platform for Udagram'

######################################################################################
#                                                                                    #
#                                      PARAMETERS                                    #
#                                                                                    #
######################################################################################

Parameters:

    EnvironmentName:
        Description: An environment name that will be prefixed to resource names
        Type: String

    VPCCIDR:
        Description: Please enter the IP range (CIDR notation) for the VPC
        Type: String
        Default: 10.0.0.0/16

    UdagramPublicSubnet1CIDR:
        Description: Please enter the IP range (CIDR notation) for the public subnet in the first Availability Zone
        Type: String
        Default: 10.0.0.0/24

    UdagramPublicSubnet2CIDR:
        Description: Please enter the IP range (CIDR notation) for the public subnet in the second Availability Zone
        Type: String
        Default: 10.0.1.0/24

    UdagramPrivateSubnet1CIDR:
        Description: Please enter the IP range (CIDR notation) for the public subnet in the first Availability Zone
        Type: String
        Default: 10.0.2.0/24

    UdagramPrivateSubnet2CIDR:
        Description: Please enter the IP range (CIDR notation) for the public subnet in the second Availability Zone
        Type: String
        Default: 10.0.3.0/24

######################################################################################
#                                                                                    #
#                                      RESOURCES                                     #
#                                                                                    #
######################################################################################

Resources:

# SPAWN VPC

    UdagramVirtualPrivateCloud:
      Type: AWS::EC2::VPC
      Properties: 
        CidrBlock: !Ref VPCCIDR
        EnableDnsHostnames: true
        Tags:
          - Key: Name
            Value: !Ref EnvironmentName

# INTERNET GATEWAY

    UdagramInternetGateway:
      Type: AWS::EC2::InternetGateway
      Properties: 
        Tags:
          - Key: Name
            Value: !Ref EnvironmentName

# INTERNET GATEWAY ATTACHMENT TO VPC

    UdagramInternetGatewayAttachment:
      Type: AWS::EC2::VPCGatewayAttachment
      Properties: 
        InternetGatewayId: !Ref UdagramInternetGateway
        VpcId: !Ref UdagramVirtualPrivateCloud

# NAT GATEWAYS

    NatGateway1EIP:
        Type: AWS::EC2::EIP
        DependsOn: UdagramInternetGatewayAttachment
        Properties: 
            Domain: vpc

    NatGateway2EIP:
        Type: AWS::EC2::EIP
        DependsOn: UdagramInternetGatewayAttachment
        Properties:
            Domain: vpc

    NatGateway1: 
        Type: AWS::EC2::NatGateway
        Properties: 
            AllocationId: !GetAtt NatGateway1EIP.AllocationId
            SubnetId: !Ref UdagramPublicSubnet1

    NatGateway2: 
        Type: AWS::EC2::NatGateway
        Properties:
            AllocationId: !GetAtt NatGateway2EIP.AllocationId
            SubnetId: !Ref UdagramPublicSubnet2

# PUBLIC SUBNETS

    UdagramPublicSubnet1: 
      Type: AWS::EC2::Subnet
      Properties:
          VpcId: !Ref UdagramVirtualPrivateCloud
          AvailabilityZone: !Select [ 0, !GetAZs '' ]
          CidrBlock: !Ref UdagramPublicSubnet1CIDR
          MapPublicIpOnLaunch: true
          Tags: 
              - Key: Name 
                Value: !Sub ${EnvironmentName} Public Subnet (AZ1)

    UdagramPublicSubnet2: 
      Type: AWS::EC2::Subnet
      Properties:
          VpcId: !Ref UdagramVirtualPrivateCloud
          AvailabilityZone: !Select [ 1, !GetAZs '' ]
          CidrBlock: !Ref UdagramPublicSubnet2CIDR
          MapPublicIpOnLaunch: true
          Tags: 
              - Key: Name 
                Value: !Sub ${EnvironmentName} Public Subnet (AZ2)

# PRIVATE SUBNETS

    UdagramPrivateSubnet1: 
        Type: AWS::EC2::Subnet
        Properties:
            VpcId: !Ref UdagramVirtualPrivateCloud
            AvailabilityZone: !Select [ 0, !GetAZs '' ]
            CidrBlock: !Ref UdagramPrivateSubnet1CIDR
            MapPublicIpOnLaunch: false
            Tags: 
                - Key: Name 
                  Value: !Sub ${EnvironmentName} Private Subnet (AZ1)

    UdagramPrivateSubnet2: 
        Type: AWS::EC2::Subnet
        Properties:
            VpcId: !Ref UdagramVirtualPrivateCloud
            AvailabilityZone: !Select [ 1, !GetAZs '' ]
            CidrBlock: !Ref UdagramPrivateSubnet2CIDR
            MapPublicIpOnLaunch: false
            Tags: 
                - Key: Name 
                  Value: !Sub ${EnvironmentName} Private Subnet (AZ2)

# PUBLIC ROUTE TABLE

    UdagramPublicRouteTable:
        Type: AWS::EC2::RouteTable
        Properties: 
            VpcId: !Ref UdagramVirtualPrivateCloud
            Tags: 
                - Key: Name 
                  Value: !Sub ${EnvironmentName} Public Route Table

    UdagramDefaultPublicRoute: 
        Type: AWS::EC2::Route
        DependsOn: UdagramInternetGatewayAttachment
        Properties: 
            RouteTableId: !Ref UdagramPublicRouteTable
            DestinationCidrBlock: 0.0.0.0/0
            GatewayId: !Ref UdagramInternetGateway

    UdagramPublicSubnet1RouteTableAssociation:
        Type: AWS::EC2::SubnetRouteTableAssociation
        Properties:
            RouteTableId: !Ref UdagramPublicRouteTable
            SubnetId: !Ref UdagramPublicSubnet1

    UdagramPublicSubnet2RouteTableAssociation:
        Type: AWS::EC2::SubnetRouteTableAssociation
        Properties:
            RouteTableId: !Ref UdagramPublicRouteTable
            SubnetId: !Ref UdagramPublicSubnet2

# PRIVATE ROUTE TABLES

    UdagramPrivateRouteTable1:
        Type: AWS::EC2::RouteTable
        Properties: 
            VpcId: !Ref UdagramVirtualPrivateCloud
            Tags: 
                - Key: Name 
                  Value: !Sub ${EnvironmentName} Private Route Table 1

    UdagramDefaultPrivateRoute1:
        Type: AWS::EC2::Route
        Properties:
            RouteTableId: !Ref UdagramPrivateRouteTable1
            DestinationCidrBlock: 0.0.0.0/0
            NatGatewayId: !Ref NatGateway1

    UdagramPrivateSubnet1RouteTableAssociation:
        Type: AWS::EC2::SubnetRouteTableAssociation
        Properties:
            RouteTableId: !Ref UdagramPrivateRouteTable1
            SubnetId: !Ref UdagramPrivateSubnet1

    UdagramPrivateRouteTable2:
        Type: AWS::EC2::RouteTable
        Properties: 
            VpcId: !Ref UdagramVirtualPrivateCloud
            Tags: 
                - Key: Name 
                  Value: !Sub ${EnvironmentName} Private Route Table 2

    UdagramDefaultPrivateRoute2:
        Type: AWS::EC2::Route
        Properties:
            RouteTableId: !Ref UdagramPrivateRouteTable2
            DestinationCidrBlock: 0.0.0.0/0
            NatGatewayId: !Ref NatGateway2

    UdagramPrivateSubnet2RouteTableAssociation:
        Type: AWS::EC2::SubnetRouteTableAssociation
        Properties:
            RouteTableId: !Ref UdagramPrivateRouteTable2
            SubnetId: !Ref UdagramPrivateSubnet2

######################################################################################
#                                                                                    #
#                                      OUTPUTS                                       #
#                                                                                    #
######################################################################################

Outputs: 

    VPC: 
        Description: A reference to the created VPC
        Value: !Ref UdagramVirtualPrivateCloud
        Export:
          Name: !Sub ${EnvironmentName}-VPCID

    PublicSubnets:
        Description: A list of the public subnets
        Value: !Join [ ",", [ !Ref UdagramPublicSubnet1, !Ref UdagramPublicSubnet2 ]]
        Export:
          Name: !Sub ${EnvironmentName}-PUB-NETS

    PublicSubnet1:
        Description: A reference to the public subnet in the 1st Availability Zone
        Value: !Ref UdagramPublicSubnet1
        Export:
          Name: !Sub ${EnvironmentName}-PUB1-SN

    PublicSubnet2: 
        Description: A reference to the public subnet in the 2nd Availability Zone
        Value: !Ref UdagramPublicSubnet2
        Export:
          Name: !Sub ${EnvironmentName}-PUB2-SN

    PrivateSubnets:
        Description: A list of the private subnets
        Value: !Join [ ",", [ !Ref UdagramPrivateSubnet1, !Ref UdagramPrivateSubnet2 ]]
        Export:
          Name: !Sub ${EnvironmentName}-PRI-NETS

    PrivateSubnet1:
        Description: A reference to the private subnet in the 1st Availability Zone
        Value: !Ref UdagramPrivateSubnet1
        Export:
          Name: !Sub ${EnvironmentName}-PRI1-SN

    PrivateSubnet2: 
        Description: A reference to the private subnet in the 2nd Availability Zone
        Value: !Ref UdagramPrivateSubnet2
        Export:
          Name: !Sub ${EnvironmentName}-PRI2-SN

    


